sudo: required

language: python

python:
    - 3.4

services:
  - docker

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y nodejs
- docker pull cloudet/pyspark-notebook-bower

install:
  - npm install

script:
- make test-python2
- make test-python3
- make sdist
- make install-python2
- make install-python3

notifications:
  email:
    on_success: change
    on_failure: always
  slack: cloudet:rMfRKhvsbZuCIRZpTct3kBI4
