language: python
python:
  - 3.5

addons:
  sauce_connect:
    no_ssl_bump_domains: all

env:
  - TEST_SERVER=ondemand.saucelabs.com TEST_TYPE=remote

before_install:
  - git clone https://github.com/ericdill/ci ~/scripts
  - . ~/scripts/install-miniconda.sh

install:
  - make env

script:
  - ./system-test/bin/run-system-test.sh

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master
    - fix-selenium
