language: python
python:
  - 3.5

addons:
  sauce_connect:
    no_ssl_bump_domains: all

before_install:
  - git clone https://github.com/ericdill/ci ~/scripts
  - . ~/scripts/install-miniconda.sh

install:
  - make env

script:
  - make test-saucelabs

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master
    - fix-selenium
